/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scrapping;

import java.io.BufferedInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class App {
    // method untuk mendownload file
    // String urlStr : alamat url file
    // String file : path lokasi file hasil download disimpan
    // diambil dari https://www.digitalocean.com/community/tutorials/java-download-file-url
    private static void downloadUsingStream(String urlStr, String file) throws IOException{
        URL url = new URL(urlStr);
        BufferedInputStream bis = new BufferedInputStream(url.openStream());
        FileOutputStream fis = new FileOutputStream(file);
        byte[] buffer = new byte[1024];
        int count=0;
        while((count = bis.read(buffer,0,1024)) != -1)
        {
            fis.write(buffer, 0, count);
        }
        fis.close();
        bis.close();
    }

    public static void main(String[] args) {
        try {
            Document doc = Jsoup.connect("https://uns.ac.id/id/category/uns-update").get();
            
            Elements media = doc.select("[src]");
            for (Element src : media) {
                // kalau tipenya img / gambar akan diunduh
                if (src.normalName().equals("img")) {
                    // print url gambar
                    System.out.println(src.attr("abs:src")); 
                    // panggil method untuk mengunduh gambar
                    // ganti /tmp dengan alamat folder untuk menyimpan gambar yang diunduh 
                    downloadUsingStream(src.attr("abs:src"), 
                    "/tmp"+"/"+src.attr("abs:src")
                    .replace("https://", "")
                    .replace("/", "_"));
                }
            }
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
